{{- if not .Values.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "octobox.fullname" . }}
  labels:
    {{- include "octobox.labels" . | nindent 4 }}
data:
  DATABASE: "postgres"

  OCTOBOX_DATABASE_HOST: {{ include "octobox.postgresqlHost" . | quote }}
  {{- if .Values.config.database.port }}
  OCTOBOX_DATABASE_PORT: {{ .Values.config.database.port | quote }}
  {{- else }}
  OCTOBOX_DATABASE_PORT: {{ .Values.postgresql.service.port | quote }}
  {{- end }}
  {{- if .Values.config.database.databaseName }}
  OCTOBOX_DATABASE_NAME: {{ .Values.config.database.databaseName | quote }}
  {{- else }}
  {{- with (set (deepCopy .) "Values" .Values.postgresql) }}
  OCTOBOX_DATABASE_NAME: {{ include "postgresql.database" . | quote }}
  {{- end }}
  {{- end }}

  {{- with .Values.config.github.domain }}
  GITHUB_DOMAIN: {{ . | quote }}
  {{- end }}
  {{- with .Values.config.github.oauth.scope }}
  GITHUB_SCOPE: {{ . | quote }}
  {{- end }}

  {{- if .Values.config.github.app }}
  GITHUB_APP_ID: {{ .Values.config.github.app.appID | required "config.github.app.appID is required" | quote }}
  GITHUB_APP_SLUG: {{ .Values.config.github.app.appSlug | required "config.github.app.appSlug is required" | quote }}
  # needed in order to process webhook events
  OCTOBOX_BACKGROUND_JOBS_ENABLED: "true"
  {{- end }}

  PERSONAL_ACCESS_TOKENS_ENABLED: {{ .Values.config.github.personalAccessTokensEnabled | quote }}

  {{- if .Values.config.github.restrictedAccess.enabled }}
  RESTRICTED_ACCESS_ENABLED: "true"
  {{- with .Values.config.github.restrictedAccess.organizationID }}
  GITHUB_ORGANIZATION_ID: {{ . | toString | quote }}
  {{- end }}
  {{- with .Values.config.github.restrictedAccess.teamID }}
  GITHUB_TEAM_ID: {{ . | toString | quote }}
  {{- end }}
  {{- end }}

  {{- with .Values.config.github.adminIDs }}
  ADMIN_GITHUB_IDS: {{ . | join "," | quote }}
  {{- end }}

  FETCH_SUBJECT: {{ .Values.config.fetchSubject | quote }}
  INCLUDE_COMMENTS: {{ .Values.config.includeComments | quote }}
  OPEN_IN_SAME_TAB: {{ .Values.config.openInSameTab | quote }}
  MINIMUM_REFRESH_INTERVAL: {{ .Values.config.minimumRefreshInterval | toString | quote }}

  RAILS_ENV: {{ .Values.config.railsEnv | quote }}
  RAILS_SERVE_STATIC_FILES: {{ .Values.config.railsServeStaticAssets | quote }}

  {{- if .Values.config.pushNotifications }}
  PUSH_NOTIFICATIONS: "true"
  {{- with .Values.config.websocketAllowedOrigins }}
  WEBSOCKET_ALLOWED_ORIGINS: {{ . | join "," | quote }}
  {{- end }}
  {{- end }}

  GA_ANALYTICS_ID: {{ .Values.config.googleAnalyticsID | quote }}
{{- end }}
