{{- if .Values.ingress.enabled -}}
{{- $fullName := include "octobox.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $nginxFullname := "nginx-static-assets" -}}
{{- with (set (deepCopy .) "Values" .Values.nginx) -}}
{{- $nginxFullname := include "common.names.fullname" . -}}
{{- end -}}
{{- $nginxPort := .Values.nginx.service.ports.http -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "octobox.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- if $.Values.nginx.enabled }}
        {{- range $.Values.ingress.staticAssetsPrefixes }}
        - path: {{ . | quote }}
          pathType: Prefix
          backend:
            service:
              name: {{ $nginxFullname }}
              port:
                number: {{ $nginxPort }}
        {{- end }}
        {{- end }}
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ $fullName }}
              port:
                number: {{ $svcPort }}
    {{- end }}
  {{- end }}
