{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "octobox.fullname" . }}-notifications
  labels:
    {{- include "octobox.labels" . | nindent 4 }}
    role: notifications-sync
spec:
  podSelector:
    matchLabels:
      {{- include "octobox.selectorLabels" . | nindent 6 }}
      role: notifications-sync
  # deny all ingress to cronjob pods
  policyTypes:
  - Ingress
{{- end }}
