{{- if and .Values.networkPolicies.enabled .Values.postgresql.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "octobox.fullname" . }}-postgres
  labels:
    {{- include "octobox.labels" . | nindent 4 }}
    role: postgres
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
  ingress:
    - ports:
        - port: tcp-postgresql
      from:
        - podSelector:
            matchLabels:
              {{- include "octobox.selectorLabels" . | nindent 14 }}
            matchExpressions:
              - key: role
                operator: In
                values:
                  - server
                  - notifications-sync
  policyTypes:
  - Ingress
{{- end }}
