{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "octobox.fullname" . }}
  labels:
    {{- include "octobox.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.config.postgresql.useServiceBinding }}
  OCTOBOX_DATABASE_USERNAME: {{ .Values.config.postgresql.username | b64enc | quote }}
  OCTOBOX_DATABASE_PASSWORD: {{ .Values.config.postgresql.password | b64enc | quote }}
  {{- end }}

  {{- if not .Values.config.redis.useServiceBinding }}
  REDIS_URL: {{ .Values.config.redis.url | b64enc | quote }}
  {{- end }}

  GITHUB_CLIENT_ID: {{ .Values.config.github.oauth.clientID | required "config.github.oauth.clientID is required" | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.config.github.oauth.clientSecret | required "config.github.oauth.clientSecret is required" | b64enc | quote }}

  {{- if .Values.config.github.app }}
  GITHUB_APP_CLIENT_ID: {{ .Values.config.github.app.clientID | required "config.github.app.clientID is required" | b64enc | quote }}
  GITHUB_APP_CLIENT_SECRET: {{ .Values.config.github.app.clientSecret | required "config.github.app.clientSecret is required" | b64enc | quote }}
  GITHUB_APP_JWT: {{ .Values.config.github.app.privateKey | required "config.github.app.privateKey is required" | b64enc | quote }}
  {{- if .Values.config.github.app.webhookSecret }}
  GITHUB_WEBHOOK_SECRET: {{ .Values.config.github.app.webhookSecret | b64enc | quote }}
  {{- end }}
  {{- end }}

  OCTOBOX_ATTRIBUTE_ENCRYPTION_KEY: {{ .Values.config.octoboxAttributeEncryptionKey | required "config.octoboxAttributeEncryptionKey is required" | b64enc | quote }}
  SECRET_KEY_BASE: {{ .Values.config.secretKeyBase | required "config.secretKeyBase is required" | b64enc | quote }}
{{- end }}
