{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "octobox.fullname" . }}
  labels:
    {{- include "octobox.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.database.username }}
  OCTOBOX_DATABASE_USERNAME: {{ .Values.config.database.username | b64enc | quote }}
  {{- else }}
  {{- with (set (deepCopy .) "Values" .Values.postgresql) }}
  OCTOBOX_DATABASE_USERNAME: {{ include "postgresql.username" . | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.config.database.password }}
  OCTOBOX_DATABASE_PASSWORD: {{ .Values.config.database.password | b64enc | quote }}
  {{- else }}
  {{- with (set (deepCopy .) "Values" .Values.postgresql) }}
  OCTOBOX_DATABASE_PASSWORD: {{ include "postgresql.password" . | b64enc | quote }}
  {{- end }}
  {{- end }}

  REDIS_URL: {{ include "octobox.redisURL" . | b64enc | quote }}

  GITHUB_CLIENT_ID: {{ .Values.config.github.oauth.clientID | required "config.github.oauth.clientID is required" | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.config.github.oauth.clientSecret | required "config.github.oauth.clientSecret is required" | b64enc | quote }}

  OCTOBOX_ATTRIBUTE_ENCRYPTION_KEY: {{ .Values.config.octoboxAttributeEncryptionKey | required "config.octoboxAttributeEncryptionKey is required" | b64enc | quote }}
  SECRET_KEY_BASE: {{ .Values.config.secretKeyBase | required "config.secretKeyBase is required" | b64enc | quote }}
{{- end }}
