{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "octobox.fullname" . }}
  labels:
    {{- include "octobox.labels" . | nindent 4 }}
type: Opaque
data:
  GITHUB_CLIENT_ID: {{ .Values.secrets.githubClientID | required "secrets.githubClientID is required" | b64enc | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.githubClientSecret | required "secrets.githubClientSecret is required" | b64enc | quote }}

  OCTOBOX_ATTRIBUTE_ENCRYPTION_KEY: {{ .Values.secrets.octoboxAttributeEncryptionKey | required "secrets.octoboxAttributeEncryptionKey is required" | b64enc | quote }}

  {{- if .Values.secrets.octoboxDatabaseUsername }}
  OCTOBOX_DATABASE_USERNAME: {{ .Values.secrets.octoboxDatabaseUsername | b64enc | quote }}
  {{- else }}
  OCTOBOX_DATABASE_USERNAME: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.octoboxDatabasePassword }}
  OCTOBOX_DATABASE_PASSWORD: {{ .Values.secrets.octoboxDatabasePassword | b64enc | quote }}
  {{- else }}
  OCTOBOX_DATABASE_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  {{- end }}

  REDIS_URL: {{ include "octobox.redisURL" . | b64enc | quote }}

  SECRET_KEY_BASE: {{ .Values.secrets.secretKeyBase | required "secrets.secretKeyBase is required" | b64enc | quote }}
{{- end }}
