{
 "title": "ISP Monitor",
 "tags": [
  "networking",
  "monitoring",
  "isp",
  "prometheus",
  "speedtest"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "target",
    "label": "Target",
    "query": {
     "query": "label_values(probe_duration_seconds,target)"
    }
   },
   {
    "name": "job",
    "label": "Probe Job",
    "query": {
     "query": "label_values(probe_duration_seconds,job)"
    }
   },
   {
    "name": "network",
    "label": "Network",
    "query": {
     "query": "label_values(probe_duration_seconds,network)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "Latest Speed Test Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "gauge",
   "description": "Shows the latency measurement from the latest speedtest results.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(speedtest_latency_milliseconds) by (mode)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "Ping" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "gauge",
   "description": "Shows the download speed measurement from the latest speedtest results.",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(speedtest_download_speed_mbps) by (mode)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "Download" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1048576" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "gauge",
   "description": "Shows the upload speed measurement from the latest speedtest results.",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(speedtest_upload_speed_mbps) by (mode)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "Download" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1048576" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Speed Test Results Over $interval",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Latency",
   "type": "stat",
   "description": "Shows the average latency measurement from speedtest results over the selected interval ($interval).",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(avg_over_time(speedtest_latency_milliseconds[$interval])) by (mode)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "Ping" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "stat",
   "description": "Shows the average download speed measurement from speedtest results over the selected interval ($interval).",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(avg_over_time(speedtest_download_speed_mbps[$interval])) by (mode)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "Download" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1048576" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "stat",
   "description": "Shows the average upload speed measurement from speedtest results over the selected interval ($interval).",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(avg_over_time(speedtest_upload_speed_mbps[$interval])) by (mode)",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "Download" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1048576" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "Speed Test Results Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(speedtest_latency_milliseconds) by (mode)"
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "sum(speedtest_download_speed_mbps) by (instance)"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "sum(speedtest_upload_speed_mbps) by (mode)"
    }
   ]
  },
  { "title": "Speed Test Result Histograms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(speedtest_latency_milliseconds_histogram_bucket[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Download Speed",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(speedtest_download_speed_mbps_histogram_bucket[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(speedtest_upload_speed_mbps_histogram_bucket[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Probe Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(probe_duration_seconds{target=~\"$target\",job=~\"$job\",network=~\"$network\"}[5m])) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}